services:
  backend:
    build: ./backend
    volumes:
      ${STANCE_DATA_PATH:-./data}: /app/data
    ports:
      - "5000:5000"
    environment:
      AUTH_URL_PATH: ${STANCE_AUTH_URL}
      DATA_DIR_PATH: /app/data
  frontend:
    build: ./frontend,
    environment:
      AUTH_URL_PATH: ${STANCE_AUTH_URL}